### ISSUE TITLE
NoMethodError: undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by u2** [nervosnetwork/ckb-demo-ruby-sdk#45] opened 2019-01-30 02:06 UTC
https://github.com/nervosnetwork/ckb-demo-ruby-sdk#user-defined-token-which-uses-only-one-cell-per-wallet

```
[130] pry(main)> bob_cell_token2.send_tokens(12345, alice_cell_token2)
NoMethodError: undefined method `[]' for nil:NilClass
from /home/u2/nervos/ckb-demo-ruby-sdk/lib/ckb/udt_wallet.rb:242:in `block in get_unspent_cells'
```

**Comment by ashchan** [comment] 2019-02-12 01:12
@u2 @classicalliu Is this not able to reproduce? Should we close this?

**Comment by classicalliu** [comment] 2019-02-12 03:06
> @u2 @classicalliu Is this not able to reproduce? Should we close this?

@u2 Do you have more informations, and does the node get any error?

**Closed** 2019-02-13 01:13 UTC
